### ISSUE TITLE
Floating point round errors for certain geometries when using string formatting

### ISSUE THREAD

**Issue by tomplex** [geomet/geomet#38]
In Python 2 and 3, using string formatting to round / truncate precision does not properly preserve coordinates. Consider the following:

```python 
from shapely.geometry import shape
from geomet import wkt

geojson = {'type': 'Point', 'coordinates': [-83.2496395, 35.917330500000006]}

geom = shape(geojson)

print(wkt.dumps(geojson))
# POINT (-83.2496395000000007 35.9173305000000056)
```

Digging deeper, it appears this is an issue with Python's implementation of rounding when done through `%` or `str.format`:

```python
fmt = '%%.%df' % 16
fmt % -83.2496395
# '-83.2496395000000007'
'{}'.format(-83.2496395)
# '-83.2496395'
'{:.16f}'.format(-83.2496395)
# '-83.2496395000000007'
```

However, when we use Python's `round()` function to achieve the desired precision, we see no mutation:

```python
round(-83.2496395, 16)
# -83.2496395
'{}'.format(round(-83.2496395, 16))
# '-83.2496395'
```

I think that this instability is undesirable in a format conversion library - for some geometries, that small coordinate shift could be the different between validity and not.

It looks like a change could rather easily be made to the codebase to use `round()` instead of relying on string interpolation. Would you be receptive to a pull request to that effect?

Thanks for your time!

**Comment by larsbutler** [comment]
Hey @tomplex,

Thanks for raising this, and thanks for the deep-dive and examples!

You are indeed correct; this rounding error is present in both Python 2.x and Python 3.x string formatting. We definitely want to fix that.

It seems like the root of the problem is here: https://github.com/geomet/geomet/blob/c48cbe8296cad5bda400b6804e546afce05073f5/geomet/wkt.py#L79.

I would absolutely accept a pull request to fix this! Even if it's a draft that I can iterate on (it doesn't need to perfect) that would be a big help.

**Comment by tomplex** [comment]
Awesome, sounds great! I look forward to working on this. I will aim to have something ready by the end of the week.
