### ISSUE TITLE
geopackage WKB

### ISSUE THREAD

**Issue by achapkowski** [geomet/geomet#42]
In Geopackages there are extra header, is there any built in support for geopackage WKB?

**Comment by larsbutler** [comment]
Hi! At the moment there is no support for gpkg formats. Is there something specific you’re looking for?

**Comment by larsbutler** [comment]
@achapkowski Apologies for the delay. So if I understand your request correctly, you need to generate and prepend the `GeoPackageBinaryHeader` to the WKB payload, right?

Do you have some examples?

**Comment by achapkowski** [comment]
No Worries.  I've below are examples for various geometries. The SRID is 4326 (WGS-1984)

Examples:

**POINT**

```python
bytearray(b'GP\x00\x01\xe6\x10\x00\x00\x01\x01\x00\x00\x00\xa8\x10O\xa9d\x91\\\xc0\x88\xec\x04\x1a}}A@')
```

**MULTIPOLYGON**

```python
bytearray(b"GP\x00\x01\xe6\x10\x00\x00\x01\x06\x00\x00\x00\x01\x00\x00\x00\x01\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00`__\xa9\xf6\x86\\\xc0\xc8\xc1\x9f`\xcd\x05B@\xd0o\xbfyz\x86\\\xc0\xb0\x1dc\xc6\x92\xabA@\xd8\xc6`D\td\\\xc0\xf8v\xe3\xfb\'\xb9A@\x88\xbd\x01z\xc2\\\\\xc0\xa8\x03\x81\x84\x17\xecA@`__\xa9\xf6\x86\\\xc0\xc8\xc1\x9f`\xcd\x05B@")
```

**MULTIPOINT**

```python
bytearray(b'GP\x00\x01Q\x96\x01\x00\x01\x04\x00\x00\x00\x03\x00\x00\x00\x01\x01\x00\x00\x00$\x94\xeeIH\xa5\\\xc0\xd0\xdb\x81\xa2H\xc5A@\x01\x01\x00\x00\x00\xd8\xe2\xfeI\xda\x9a\\\xc0\xe8G\x821\xe1\xb1A@\x01\x01\x00\x00\x00\x14\x7f\x8f\x85>\x96\\\xc0\x00\xea"\xcc\x87\xcdA@')
```

**MULTILINESTRING**

```python
bytearray(b'GP\x00\x01\xe6\x10\x00\x00\x01\x05\x00\x00\x00\x01\x00\x00\x00\x01\x02\x00\x00\x00\x02\x00\x00\x00\xd4\x8b]\x7fK\xbd\\\xc0\xd8\xe2!\xc6J\xd5A@\xccb\xce\xd8\xbc\xa6\\\xc0 \xf3\xbf\xd1X\x04B@')
```

This is all for the 1.2.1 specification of Geopackage geometry.

**Comment by larsbutler** [comment]
@achapkowski Thanks for the examples. I need a little more context, though:

- Could you post what these geometries are supposed to be in WKT or GeoJSON? 
- What is the endianness? It looks like little endian. 

That would help me a lot so I don't have to decipher a new binary protocol from scratch. :)

**Comment by achapkowski** [comment]
Sorry for the delay: https://www.geopackage.org/spec121/index.html#gpb_format

**Comment by DavidMStraub** [comment]
Hi,

I found this issue when also looking for this functionality. My use case is loading part of a huge Geopackage file using raw SQL queries. This works perfectly, except that I cannot parse the geometry blobs (yet). Is there any progress on this issue or anything I can do to help?

I know that Geopandas can read Geopackage via GDAL, but that doesn't help me as it apparently only works when loading the entire file (which is not feasible for me).

**Comment by DavidMStraub** [comment]
BTW, I found this very old pull request in shapely:
https://github.com/Toblerity/Shapely/pull/103
Doesn't this already contain the necessary code?

**Comment by larsbutler** [comment]
Hi @DavidMStraub,

> BTW, I found this very old pull request in shapely:
> Toblerity/Shapely#103
> Doesn't this already contain the necessary code?

It definitely looks like some of the work is done. However, it looks like this parser is dropping the envelope which seems kind of important for GeoPackage.

> Is there any progress on this issue or anything I can do to help?

Yes, there is! It would be great if you can provide some sample inputs/outputs for the GPB blobs, with and without envelope. Looking again at the spec again, it seems that the binary format is basically just WKB prepended with an additional header. Shouldn't be much work to implement, but I maintain this library in my free time and good test cases are half the effort.

Do you have some cases you could share?

> I know that Geopandas can read Geopackage via GDAL, but that doesn't help me as it apparently only works when loading the entire file (which is not feasible for me).

Just so I understand the problem and use case: You want to be able to read individual geometries in blob form from a GeoPackage (SQLite) file, without having to ingest the entire package file?

**Comment by DavidMStraub** [comment]
> Do you have some cases you could share?

I'll have a look. Actually, since Geopandas supports import/export of Geopackage for entire files, the easiest way (for me) to generate valid examples would probably be by generating them in this way.

> Just so I understand the problem and use case: You want to be able to read individual geometries in blob form from a GeoPackage (SQLite) file, without having to ingest the entire package file?

Yes. What I'm doing is basically the SQLite analogue of Geopanda's [`read_postgis`](https://github.com/geopandas/geopandas/blob/master/geopandas/io/sql.py). Using `pandas.read_sql_query`, I'm getting a `DataFrame` with binary blobs for the geometry column, and I need to parse them to turn it into a `GeoDataFrame` (for PostGIS, this is done by `shapely`, but for Geopackage it doesn't work due to the rejected PR linked above).

**Comment by DavidMStraub** [comment]
Here is a super primitive snippet to use Geopandas to create a GPKG and read the created blob back in:

```python
import geopandas as gpd
from geojson import Feature
import sqlite3
import tempfile

def geometry_to_blob(gc: dict) -> bytes:
    gdf = gpd.GeoDataFrame.from_features([Feature(geometry=gc)])
    with tempfile.NamedTemporaryFile() as fp:
        gdf.to_file(fp, driver="GPKG")
        con = sqlite3.connect(fp.name)
        cursor = con.cursor()
        cursor.execute("SELECT table_name FROM gpkg_contents;")
        tablename = cursor.fetchone()[0]
        cursor.execute(f"SELECT * FROM '{tablename}';")
        blob = cursor.fetchone()[1]
        con.close()
    return blob
```

This could be used to generate the test cases needed for a GPKG analogue of [this test](https://github.com/geomet/geomet/blob/master/geomet/tests/wkb_test.py). I cheked it works for instance with this geometry collection taken from this test:

```python
gc = dict(type='GeometryCollection', geometries=[
            dict(type='Point', coordinates=[0.0, 1.0]),
            dict(type='LineString', coordinates=[
                [102.0, 2.0], [103.0, 3.0], [104.0, 4.0]
            ]),
])
```

**Comment by achapkowski** [comment]
Here is my super hacky version of working with the WKB based on this package: https://github.com/achapkowski/pygeopackage/blob/master/src/geopackage/_wkb.py

**Comment by phidrho** [comment]
Hi @larsbutler 
I'm not a programmer, but I can prepare data for you in WKB and WKT (with help of QGIS plugin Plain Geometry editor) as well as geopackage files for any kind of data if needed.

I was just recently browsing for this solution, and here is what I found, it might help you:

> Yes, there is! It would be great if you can provide some sample inputs/outputs for the GPB blobs, with and without envelope. Looking again at the spec again, it seems that the binary format is basically just WKB prepended with an additional header. Shouldn't be much work to implement, but I maintain this library in my free time and good test cases are half the effort.

Yes, you are correct, it is WKB with an additional header, and they added header because of SQLite limitations, explained here:
https://github.com/opengeospatial/geopackage/issues/335#issuecomment-291154376

I also found this, which also might be of help:

JavaScript
- http://ngageoint.github.io/geopackage-js/jsdoc/geom_geometryData.js.html

Java
- https://github.com/ngageoint/geopackage-core-java/blob/master/src/main/java/mil/nga/geopackage/geom/GeoPackageGeometryData.java

**Comment by larsbutler** [comment]
> I'll have a look. Actually, since Geopandas supports import/export of Geopackage for entire files, the easiest way (for me) to generate valid examples would probably be by generating them in this way.

Cool, sounds like a sensible approach.

**Comment by larsbutler** [comment]
@phidrho 

> I'm not a programmer, but I can prepare data for you in WKB and WKT (with help of QGIS plugin Plain Geometry editor) as well as geopackage files for any kind of data if needed.

Awesome, that would be helpful to ensure that the implementation is correct.

**Comment by phidrho** [comment]
Hi,
I managed to prepare some data.
There is geopackage "examples.gpkg" file with many layers which represent different [geometry types] (http://www.geopackage.org/spec121/index.html#geometry_types), all data is unprojected (coordinates are in lat/lon EPSG:4326).

Each layer is it's own table and has
- fid column = feature id 
- geometry column  = geopackage WKB
- WKT column = WKT representation of geo data

I created it with QGIS 3.10, and I believe it uses GDAL in the background for writing data to geopackage file.
I also saved all layers to geojson format.

[examples.gpkg.zip](https://github.com/geomet/geomet/files/4051632/examples.gpkg.zip)
[geojson.zip](https://github.com/geomet/geomet/files/4051633/geojson.zip)
[layer description.txt](https://github.com/geomet/geomet/files/4051635/layer.description.txt)

Tomorrow I plan to project data to some common projection for Europe, so we would have additional examples.

If you notice anything weird, please contact me and I'll check for errors since I did almost all manually (I didn't create data with script) and I could have made a mistake somewhere.

**Comment by larsbutler** [comment]
Hey @phidrho, these are great examples! The conversion looks fairly straightforward. Thanks for taking the time to put those together. :)

One question: Do any of these have examples of GeoPackage envelopes? I haven't looked all of them yet.

**Comment by phidrho** [comment]
> One question: Do any of these have examples of GeoPackage envelopes? I haven't looked all of them yet.

I haven't prepared envelope data because I thought It wasn't relevant, it should be generated programmatically from the data source. In the current version of QGIS there are functions for extracting from WKT:

- y_min, y_max
- x_min, x_max

but functions for extracting

- m_min, m_max,
- z_min, z_max

from WKT values are missing, so there's no quick solution currently.

I would have to create a python script to pull that data out. I don't think that I'll be able to do this before the weekend.

I'll report missing features to QGIS development team.

**Comment by achapkowski** [comment]
In esri JSON there is properties on the geometry that lets you know if that data exists:

```
{
  "hasM" : true | false,
  "hasZ" : true | false,
  "points" : [[ <x1>, <y1>, <z1>, <m1> ] , [ <x2>, <y2>, <z2>, <m2> ], ... ], 
  "spatialReference" : {<spatialReference>}
}
```

See: https://developers.arcgis.com/documentation/common-data-types/geometry-objects.htm

Sample Data for Point, Polygon and Polyline.

[point.zip](https://github.com/geomet/geomet/files/4159508/point.zip)


[polygon_data.zip](https://github.com/geomet/geomet/files/4159499/polygon_data.zip)
[polyline.zip](https://github.com/geomet/geomet/files/4159505/polyline.zip)

**Comment by tomplex** [comment]
Hey folks, I'm working on this implementation but I had a question. There's an item in the GeoJSON spec which refers to [bounding boxes](https://tools.ietf.org/html/rfc7946#section-5), but it specifies that the bounding box should live at the feature level, not the geometry level. Obviously `geomet` outputs just the geometries, and I don't think we want to simply discard this information, because we want any transformation from geopackage <-> geojson to be lossless. Where should we put it? @larsbutler put srid information in a `'meta'` key on the geojson like so:

```python
{
    'type': 'Point',
    'coordinates': [0, 0],
    'meta': {
        'srid': 4326
    }
}
```

Should we follow suit and put the envelope in there too? Like...

```python
{
    'type': 'Point',
    'coordinates': [0, 0],
    'meta': {
        'srid': 4326,
        'envelope': [0, 0, 0, 0]
    }
}
```
Or should it be a top-level member of the geojson?

```python
{
    'type': 'Point',
    'coordinates': [0, 0],
    'meta': {
        'srid': 4326
    }
    'envelope': [0, 0, 0, 0]
}
```

There's also the item of naming. The spec linked above calls the item `'bbox'`; should we follow suit or preserve the geopackage naming standard of `'envelope'`?

Thanks for your input!

**Comment by achapkowski** [comment]
I think bbox is fine since most interchange the two keys.  I would ensure that in the doc, you just explain what bbox is.
