### ISSUE TITLE
README not rendering correctly on PyPI

### ISSUE THREAD

**Issue by larsbutler** [geomet/geomet#88]
The [PyPI page](https://pypi.org/project/geomet/) has essentially blank documentation. If we use [readme-renderer](https://pypi.org/project/readme-renderer/), we directly render the contents of REAMDE.md and fix this issue.

Basically, this requires amending the setup.py and setting the `long_description` to the contents of the README.md file.

**Comment by glenn-jocher** [comment]
@larsbutler hi! Apologies in advance for being off-topic, but I couldn't figure out how to reach you. 

I'm Glenn, author of YOLOv5 (https://github.com/ultralytics/yolov5), a popular AI that makes vision tasks like detection and classification easy for students and organizations. In the two years since we launched, it has since grown into one of the most popular AI's in the world, with 300 contributors 34,000 GitHub stars, and has inspired new vision architectures by multiple groups around the world.

I'm now working on a new project that will be a single home for all YOLO models, with common import and export formats, and cross-compatibility with the most popular deployment tools like Microsoft's ONNX, Apple's CoreML and Google's TensorFlow.

I'm writing because I'd love to be able to use the `yolo` pip package name for simple deployment of our tool, i.e. `pip install yolo`, and I see that you are the current owner and that it appears that it is not actively being used.

I'd love to chat and explain our vision for the yolo package, and to allow you to meet our team and ask any questions you have. Please select a time here that suits you, or feel free to respond by email at glenn.jocher@ultralytics.com.
https://calendly.com/ultralytics/meet

Thank you!
